export default class VideoPublishTask {
  id: number;
  filePath: string;
  fileName: string;
  title: string;
  description: number;
  topic: string;
  platformData: string;
  accountId: string;
  platformId: number;
  publishType: number;
  publishTime: string;
  scheduledStartTime: string;
  startTime: string;
  endTime: string;
  status: number;
  itemId: string;
  collectCount: number;
  commentCount: number;
  diggCount: number;
  forwardCount: number;
  liveWatchCount: number;
  playCount: number;
  shareCount: number;
  cityName: string;
  tagName: string;
  createdAt: string;
  updatedAt: string;
}